// key是搜索内容 value是录入内容
var tipMap = [
    //空
    ["left" , "left" , "" ],
    ["right" , "right" , "" ],
    ["quad" , "quad" , "\\quad" ],
    ["qquad" , "qquad" , "\\qquad" ],
    ["mathit" , "mathit" , "" ],
    ["unicode" , "unicode{x}" , "" , -2 ],
    
    //符号大小
    ["big" , "big" , "" ],
    ["Big" , "Big" , "" ],
    ["bigg" , "bigg" , "" ],
    ["Bigg" , "Bigg" , "" ],

    //左右括号大小
    ["bigl" , "bigl" , "" ],
    ["Bigl" , "Bigl" , "" ],
    ["biggl" , "biggl" , "" ],
    ["Biggl" , "Biggl" , "" ],
    ["Biggr" , "Biggr" , "" ],
    ["biggr" , "biggr" , "" ],
    ["Bigr" , "Bigr" , "" ],
    ["bigr" , "bigr" , "" ],

    //希腊字母
    ["alpha" , "alpha" , "\\alpha"],
    ["beta" , "beta" , "\\beta"],
    ["gamma" , "gamma" , "\\gamma"],
    ["delta" , "delta" , "\\delta"],
    ["nabla" , "nabla" , "\\nabla"],
    ["epsilon" , "epsilon" , "\\epsilon"],
    ["varepsilon" , "varepsilon" , "\\varepsilon"],
    ["zeta" , "zeta" , "\\zeta"],
    ["eta" , "eta" , "\\eta"],
    ["theta" , "theta" , "\\theta"],
    ["vartheta" , "vartheta" , "\\vartheta"],
    ["iota" , "iota" , "\\iota"],
    ["kappa" , "kappa" , "\\kappa"],
    ["lambda" , "lambda" , "\\lambda"],
    ["mu" , "mu" , "\\mu"],
    ["nu" , "nu" , "\\nu"],
    ["xi" , "xi" , "\\xi"],
    // ["o" , "o" , "o"], 特殊
    ["pi" , "pi" , "\\pi"],

    ["varpi" , "varpi" , "\\varpi"],
    ["rho" , "rho" , "\\rho"],

    ["varrho" , "varrho" , "\\varrho"],
    ["sigma" , "sigma" , "\\sigma"],
    ["varsigma" , "varsigma" , "\\varsigma"],
    ["tau" , "tau" , "\\tau"],
    ["upsilon" , "upsilon" , "\\upsilon"],
    ["phi" , "phi" , "\\phi"],
    ["varphi" , "varphi" , "\\varphi"],
    ["chi" , "chi" , "\\chi"],
    ["psi" , "psi" , "\\psi"],
    ["omega" , "omega" , "\\omega"],
    ["Gamma" , "Gamma" , "\\Gamma"],
    ["Delta" , "Delta" , "\\Delta"],

    ["Theta" , "Theta" , "\\Theta"],
    ["Lambda" , "Lambda" , "\\Lambda"],
    ["Xi" , "Xi" , "\\Xi"],
    ["Pi" , "Pi" , "\\Pi"],
    ["Sigma" , "Sigma" , "\\Sigma"],
    ["Upsilon" , "Upsilon" , "\\Upsilon"],
    ["Phi" , "Phi" , "\\Phi"],
    ["Psi" , "Psi" , "\\Psi"],
    ["Omega" , "Omega" , "\\Omega"],


    //希伯来字母
    ["aleph" , "aleph" , "\\aleph"],
    ["beth" , "beth" , "\\beth"],
    ["gimel" , "gimel" , "\\gimel"],
    ["daleth" , "daleth" , "\\daleth"],

    //二元运算符
    // ["+" , "+" , "+"],
    // ["-" , "-" , "-"],
    ["times" , "times" , "\\times"],
    ["div" , "div" , "\\div"],
    ["pm" , "pm" , "\\pm"],
    ["mp" , "mp" , "\\mp"],
    ["triangleleft" , "triangleleft" , "\\triangleleft"],
    ["triangleright" , "triangleright" , "\\triangleright"],
    ["cdot" , "cdot" , "\\cdot"],
    ["setminus" , "setminus" , "\\setminus"],
    ["star" , "star" , "\\star"],
    ["ast" , "ast" , "\\ast"],
    ["circ" , "circ" , "\\circ"],
    ["bullet" , "bullet" , "\\bullet"],
    ["oplus" , "oplus" , "\\oplus"],
    ["ominus" , "ominus" , "\\ominus"],
    ["odot" , "odot" , "\\odot"],
    ["oslash" , "oslash" , "\\oslash"],
    ["otimes" , "otimes" , "\\otimes"],
    ["bigtriangleup" , "bigtriangleup" , "\\bigtriangleup"],
    ["lhd" , "lhd" , "\\lhd"],
    ["rhd" , "rhd" , "\\rhd"],
    ["unlhd" , "unlhd" , "\\unlhd"],
    ["unrhd" , "unrhd" , "\\unrhd"],
    ["amalg" , "amalg" , "\\amalg"],
    ["dagger" , "dagger" , "\\dagger"],

    //二元关系符
    // ["=" , "=" , "="],
    ["ne" , "ne" , "\\ne"],
    ["neq" , "neq" , "\\neq"],
    ["equiv" , "equiv" , "\\equiv"],
    ["notequiv" , "not\\equiv" , "\\not\\equiv"],
    ["doteq" , "doteq" , "\\doteq"],
    ["doteqdot" , "doteqdot" , "\\doteqdot"],

    ["underset" , "underset{}{}" , "\\underset{u}{\\Box}", -4],
    ["overset" , "overset{}{}" , "\\overset{u}{\\Box}", -4],

    ["sim" , "sim" , "\\sim"],
    ["nsim" , "nsim" , "\\nsim"],
    ["backsim" , "backsim" , "\\backsim"],
    ["thicksim" , "thicksim" , "\\thicksim"],
    ["simeq" , "simeq" , "\\simeq"],
    ["backsimeq" , "backsimeq" , "\\backsimeq"],
    ["eqsim" , "eqsim" , "\\eqsim"],
    ["cong" , "cong" , "\\cong"],
    ["ncong" , "ncong" , "\\ncong"],
    ["approx" , "approx" , "\\approx"],
    ["thickapprox" , "thickapprox" , "\\thickapprox"],
    ["approxeq" , "approxeq" , "\\approxeq"],
    ["asymp" , "asymp" , "\\asymp"],
    ["propto" , "propto" , "\\propto"],
    ["varpropto" , "varpropto" , "\\varpropto"],
    ["lt" , "lt" , "\\lt"],
    ["nless" , "nless" , "\\nless"],
    ["ll" , "ll" , "\\ll"],
    ["notll" , "not\\ll" , "\\not\\ll"],
    ["lll" , "lll" , "\\lll"],
    ["notlll" , "not\\lll" , "\\not\\lll"],
    ["lessdot" , "lessdot" , "\\lessdot"],
    ["gt" , "gt" , "\\gt"],
    ["ngtr" , "ngtr" , "\\ngtr"],
    ["gg" , "gg" , "\\gg"],
    ["notgg" , "not\\gg" , "\\not\\gg"],
    ["ggg" , "ggg" , "\\ggg"],
    ["notggg" , "not\\ggg" , "\\not\\ggg"],
    ["gtrdot" , "gtrdot" , "\\gtrdot"],
    ["le" , "le" , "\\le"],
    ["leq" , "leq" , "\\leq"],
    ["lneq" , "lneq" , "\\lneq"],
    ["leqq" , "leqq" , "\\leqq"],
    ["nleq" , "nleq" , "\\nleq"],
    ["nleqq" , "nleqq" , "\\nleqq"],
    ["lneqq" , "lneqq" , "\\lneqq"],
    ["ge" , "ge" , "\\ge"],
    ["geq" , "geq" , "\\geq"],
    ["gneq" , "gneq" , "\\gneq"],
    ["geqq" , "geqq" , "\\geqq"],
    ["ngeq" , "ngeq" , "\\ngeq"],
    ["gneqq" , "gneqq" , "\\gneqq"],
    ["gvertneqq" , "gvertneqq" , "\\gvertneqq"],
    ["lessgtr" , "lessgtr" , "\\lessgtr"],
    ["lesseqgtr" , "lesseqgtr" , "\\lesseqgtr"],
    ["lesseqqgtr" , "lesseqqgtr" , "\\lesseqqgtr"],
    ["gtrless" , "gtrless" , "\\gtrless"],
    ["gtreqless" , "gtreqless" , "\\gtreqless"],
    ["leqslant" , "leqslant" , "\\leqslant"],
    ["nleqslant" , "nleqslant" , "\\nleqslant"],
    ["eqslantless" , "eqslantless" , "\\eqslantless"],
    ["geqslant" , "geqslant" , "\\geqslant"],
    ["ngeqslant" , "ngeqslant" , "\\ngeqslant"],
    ["eqslantgtr" , "eqslantgtr" , "\\eqslantgtr"],
    ["lesssim" , "lesssim" , "\\lesssim"],
    ["lnsim" , "lnsim" , "\\lnsim"],
    ["lessapprox" , "lessapprox" , "\\lessapprox"],
    ["lnapprox" , "lnapprox" , "\\lnapprox"],
    ["gtrsim" , "gtrsim" , "\\gtrsim"],
    ["gnsim" , "gnsim" , "\\gnsim"],
    ["gtrapprox" , "gtrapprox" , "\\gtrapprox"],
    ["gnapprox" , "gnapprox" , "\\gnapprox"],
    ["prec" , "prec" , "\\prec"],
    ["nprec" , "nprec" , "\\nprec"],
    ["preceq" , "preceq" , "\\preceq"],
    ["npreceq" , "npreceq" , "\\npreceq"],
    ["precneqq" , "precneqq" , "\\precneqq"],
    ["succ" , "succ" , "\\succ"],
    ["nsucc" , "nsucc" , "\\nsucc"],
    ["succeq" , "succeq" , "\\succeq"],
    ["nsucceq" , "nsucceq" , "\\nsucceq"],
    ["succneqq" , "succneqq" , "\\succneqq"],
    ["preccurlyeq" , "preccurlyeq" , "\\preccurlyeq"],
    ["curlyeqprec" , "curlyeqprec" , "\\curlyeqprec"],
    ["succcurlyeq" , "succcurlyeq" , "\\succcurlyeq"],
    ["curlyeqsucc" , "curlyeqsucc" , "\\curlyeqsucc"],
    ["precsim" , "precsim" , "\\precsim"],
    ["precnsim" , "precnsim" , "\\precnsim"],
    ["precapprox" , "precapprox" , "\\precapprox"],
    ["precnapprox" , "precnapprox" , "\\precnapprox"],
    ["succsim" , "succsim" , "\\succsim"],
    ["succnsim" , "succnsim" , "\\succnsim"],
    ["succapprox" , "succapprox" , "\\succapprox"],
    ["succnapprox" , "succnapprox" , "\\succnapprox"],

    //几何符号
    ["parallel" , "parallel" , "\\parallel"],
    ["nparallel" , "nparallel" , "\\nparallel"],
    ["shortparallel" , "shortparallel" , "\\shortparallel"],
    ["nshortparallel" , "nshortparallel" , "\\nshortparallel"],
    ["perp" , "perp" , "\\perp"],
    ["angle" , "angle" , "\\angle"],
    ["sphericalangle" , "sphericalangle" , "\\sphericalangle"],
    ["measuredangle" , "measuredangle" , "\\measuredangle"],
    ["Box" , "Box" , "\\Box"],
    ["blacksquare" , "blacksquare" , "\\blacksquare"],
    ["diamond" , "diamond" , "\\diamond"],
    ["Diamond" , "Diamond" , "\\Diamond"],
    ["lozenge" , "lozenge" , "\\lozenge"],
    ["blacklozenge" , "blacklozenge" , "\\blacklozenge"],
    ["bigstar" , "bigstar" , "\\bigstar"],
    ["bigcirc" , "bigcirc" , "\\bigcirc"],
    ["triangle" , "triangle" , "\\triangle"],
    ["bigtriangledown" , "bigtriangledown" , "\\bigtriangledown"],
    ["vartriangle" , "vartriangle" , "\\vartriangle"],
    ["triangledown" , "triangledown" , "\\triangledown"],
    ["blacktriangle" , "blacktriangle" , "\\blacktriangle"],
    ["blacktriangledown" , "blacktriangledown" , "\\blacktriangledown"],
    ["blacktriangleleft" , "blacktriangleleft" , "\\blacktriangleleft"],
    ["blacktriangleright" , "blacktriangleright" , "\\blacktriangleright"],

    //逻辑符号
    ["forall" , "forall" , "\\forall"],
    ["exists" , "exists" , "\\exists"],
    ["nexists" , "nexists" , "\\nexists"],
    ["therefore" , "therefore" , "\\therefore"],
    ["because" , "because" , "\\because"],
    ["And" , "And" , "\\And"],
    ["lor" , "lor" , "\\lor"],
    ["vee" , "vee" , "\\vee"],
    ["curlyvee" , "curlyvee" , "\\curlyvee"],
    ["bigvee" , "bigvee" , "\\bigvee"],
    ["land" , "land" , "\\land"],
    ["wedge" , "wedge" , "\\wedge"],
    ["curlywedge" , "curlywedge" , "\\curlywedge"],
    ["bigwedge" , "bigwedge" , "\\bigwedge"],
    ["bar" , "bar{}" , "\\bar{q}" , -2],
    ["overline" , "overline{}" , "\\overline{abc}" , -2],
    ["lnot" , "lnot" , "\\lnot"],
    ["notoperatorname" , "not\\operatorname{}" , "\\not\\operatorname{R}" , -2],
    ["bot" , "bot" , "\\bot"],
    ["top" , "top" , "\\top"],
    ["vdash" , "vdash" , "\\vdash"],
    ["dashv" , "dashv" , "\\dashv"],
    ["Vdash" , "Vdash" , "\\Vdash"],
    ["models" , "models" , "\\models"],
    ["Vvdash" , "Vvdash" , "\\Vvdash"],
    ["nvdash" , "nvdash" , "\\nvdash"],
    ["nVdash" , "nVdash" , "\\nVdash"],
    ["nvDash" , "nvDash" , "\\nvDash"],
    ["nVDash" , "nVDash" , "\\nVDash"],
    ["ulcorner" , "ulcorner" , "\\ulcorner"],
    ["urcorner" , "urcorner" , "\\urcorner"],
    ["llcorner" , "llcorner" , "\\llcorner"],
    ["lrcorner" , "lrcorner" , "\\lrcorner"],


    //集合
    ["emptyset" , "emptyset" , "\\emptyset"],
    ["varnothing" , "varnothing" , "\\varnothing"],
    ["in" , "in" , "\\in"],
    ["notin" , "notin" , "\\notin"],
    ["ni" , "ni" , "\\ni"],
    ["cap" , "cap" , "\\cap"],
    ["Cap" , "Cap" , "\\Cap"],
    ["sqcap" , "sqcap" , "\\sqcap"],
    ["bigcap" , "bigcap" , "\\bigcap"],
    ["cup" , "cup" , "\\cup"],
    ["Cup" , "Cup" , "\\Cup"],
    ["sqcup" , "sqcup" , "\\sqcup"],
    ["bigcup" , "bigcup" , "\\bigcup"],
    ["bigsqcup" , "bigsqcup" , "\\bigsqcup"],
    ["uplus" , "uplus" , "\\uplus"],
    ["biguplus" , "biguplus" , "\\biguplus"],
    ["smallsetminus" , "smallsetminus" , "\\smallsetminus"],
    ["subset" , "subset" , "\\subset"],
    ["Subset" , "Subset" , "\\Subset"],
    ["sqsubset" , "sqsubset" , "\\sqsubset"],
    ["supset" , "supset" , "\\supset"],
    ["Supset" , "Supset" , "\\Supset"],
    ["sqsupset" , "sqsupset" , "\\sqsupset"],
    ["subseteq" , "subseteq" , "\\subseteq"],
    ["nsubseteq" , "nsubseteq" , "\\nsubseteq"],
    ["subsetneq" , "subsetneq" , "\\subsetneq"],
    ["varsubsetneq" , "varsubsetneq" , "\\varsubsetneq"],
    ["sqsubseteq" , "sqsubseteq" , "\\sqsubseteq"],
    ["supseteq" , "supseteq" , "\\supseteq"],
    ["nsupseteq" , "nsupseteq" , "\\nsupseteq"],
    ["supsetneq" , "supsetneq" , "\\supsetneq"],
    ["varsupsetneq" , "varsupsetneq" , "\\varsupsetneq"],
    ["sqsupseteq" , "sqsupseteq" , "\\sqsupseteq"],
    ["subseteqq" , "subseteqq" , "\\subseteqq"],
    ["nsubseteqq" , "nsubseteqq" , "\\nsubseteqq"],
    ["subsetneqq" , "subsetneqq" , "\\subsetneqq"],
    ["varsubsetneqq" , "varsubsetneqq" , "\\varsubsetneqq"],
    ["supseteqq" , "supseteqq" , "\\supseteqq"],
    ["nsupseteqq" , "nsupseteqq" , "\\nsupseteqq"],
    ["supsetneqq" , "supsetneqq" , "\\supsetneqq"],
    ["varsupsetneqq" , "varsupsetneqq" , "\\varsupsetneqq"],


    //箭头
    ["Rrightarrow" , "Rrightarrow" , "\\Rrightarrow"],
    ["Lleftarrow" , "Lleftarrow" , "\\Lleftarrow"],
    ["Rightarrow" , "Rightarrow" , "\\Rightarrow"],
    ["nRightarrow" , "nRightarrow" , "\\nRightarrow"],
    ["Longrightarrow" , "Longrightarrow" , "\\Longrightarrow"],
    ["implies" , "implies" , "\\implies"],
    ["Leftarrow" , "Leftarrow" , "\\Leftarrow"],
    ["nLeftarrow" , "nLeftarrow" , "\\nLeftarrow"],
    ["Longleftarrow" , "Longleftarrow" , "\\Longleftarrow"],
    ["Leftrightarrow" , "Leftrightarrow" , "\\Leftrightarrow"],
    ["nLeftrightarrow" , "nLeftrightarrow" , "\\nLeftrightarrow"],
    ["Longleftrightarrow" , "Longleftrightarrow" , "\\Longleftrightarrow"],
    ["iff" , "iff" , "\\iff"],
    ["Uparrow" , "Uparrow" , "\\Uparrow"],
    ["Downarrow" , "Downarrow" , "\\Downarrow"],
    ["Updownarrow" , "Updownarrow" , "\\Updownarrow"],
    ["rightarrow" , "rightarrow" , "\\rightarrow"],
    ["to" , "to" , "\\to"],
    ["nrightarrow" , "nrightarrow" , "\\nrightarrow"],
    ["longrightarrow" , "longrightarrow" , "\\longrightarrow"],
    ["leftarrow" , "leftarrow" , "\\leftarrow"],
    ["gets" , "gets" , "\\gets"],
    ["nleftarrow" , "nleftarrow" , "\\nleftarrow"],
    ["longleftarrow" , "longleftarrow" , "\\longleftarrow"],
    ["leftrightarrow" , "leftrightarrow" , "\\leftrightarrow"],
    ["nleftrightarrow" , "nleftrightarrow" , "\\nleftrightarrow"],
    ["longleftrightarrow" , "longleftrightarrow" , "\\longleftrightarrow"],
    ["uparrow" , "uparrow" , "\\uparrow"],
    ["downarrow" , "downarrow" , "\\downarrow"],
    ["updownarrow" , "updownarrow" , "\\updownarrow"],
    ["nearrow" , "nearrow" , "\\nearrow"],
    ["swarrow" , "swarrow" , "\\swarrow"],
    ["nwarrow" , "nwarrow" , "\\nwarrow"],
    ["searrow" , "searrow" , "\\searrow"],
    ["mapsto" , "mapsto" , "\\mapsto"],
    ["longmapsto" , "longmapsto" , "\\longmapsto"],
    ["rightharpoonup" , "rightharpoonup" , "\\rightharpoonup"],
    ["rightharpoondown" , "rightharpoondown" , "\\rightharpoondown"],
    ["leftharpoonup" , "leftharpoonup" , "\\leftharpoonup"],
    ["leftharpoondown" , "leftharpoondown" , "\\leftharpoondown"],
    ["upharpoonleft" , "upharpoonleft" , "\\upharpoonleft"],
    ["upharpoonright" , "upharpoonright" , "\\upharpoonright"],
    ["downharpoonleft" , "downharpoonleft" , "\\downharpoonleft"],
    ["downharpoonright" , "downharpoonright" , "\\downharpoonright"],
    ["rightleftharpoons" , "rightleftharpoons" , "\\rightleftharpoons"],
    ["leftrightharpoons" , "leftrightharpoons" , "\\leftrightharpoons"],
    ["curvearrowleft" , "curvearrowleft" , "\\curvearrowleft"],
    ["circlearrowleft" , "circlearrowleft" , "\\circlearrowleft"],
    ["Lsh" , "Lsh" , "\\Lsh"],
    ["upuparrows" , "upuparrows" , "\\upuparrows"],
    ["rightrightarrows" , "rightrightarrows" , "\\rightrightarrows"],
    ["rightleftarrows" , "rightleftarrows" , "\\rightleftarrows"],
    ["rightarrowtail" , "rightarrowtail" , "\\rightarrowtail"],
    ["looparrowright" , "looparrowright" , "\\looparrowright"],
    ["curvearrowright" , "curvearrowright" , "\\curvearrowright"],
    ["circlearrowright" , "circlearrowright" , "\\circlearrowright"],
    ["Rsh" , "Rsh" , "\\Rsh"],
    ["downdownarrows" , "downdownarrows" , "\\downdownarrows"],
    ["leftleftarrows" , "leftleftarrows" , "\\leftleftarrows"],
    ["leftrightarrows" , "leftrightarrows" , "\\leftrightarrows"],
    ["leftarrowtail" , "leftarrowtail" , "\\leftarrowtail"],
    ["looparrowleft" , "looparrowleft" , "\\looparrowleft"],
    ["hookrightarrow" , "hookrightarrow" , "\\hookrightarrow"],
    ["hookleftarrow" , "hookleftarrow" , "\\hookleftarrow"],
    ["multimap" , "multimap" , "\\multimap"],
    ["leftrightsquigarrow" , "leftrightsquigarrow" , "\\leftrightsquigarrow"],
    ["rightsquigarrow" , "rightsquigarrow" , "\\rightsquigarrow"],
    ["twoheadrightarrow" , "twoheadrightarrow" , "\\twoheadrightarrow"],
    ["twoheadleftarrow" , "twoheadleftarrow" , "\\twoheadleftarrow"],

    //特殊
    ["infty" , "infty" , "\\infty"],
    ["complement" , "complement" , "\\complement"],
    ["backepsilon" , "backepsilon" , "\\backepsilon"],
    ["eth" , "eth" , "\\eth"],
    ["Finv" , "Finv" , "\\Finv"],
    ["hbar" , "hbar" , "\\hbar"],
    ["Im" , "Im" , "\\Im"],
    ["imath" , "imath" , "\\imath"],
    ["jmath" , "jmath" , "\\jmath"],
    ["Bbbk" , "Bbbk" , "\\Bbbk"],
    ["ell" , "ell" , "\\ell"],
    ["mho" , "mho" , "\\mho"],
    ["wp" , "wp" , "\\wp"],
    ["Re" , "Re" , "\\Re"],
    ["circledS" , "circledS" , "\\circledS"],
    ["ddagger" , "ddagger" , "\\ddagger"],
    ["ldots" , "ldots" , "\\ldots"],
    ["cdots" , "cdots" , "\\cdots"],
    ["smile" , "smile" , "\\smile"],
    ["frown" , "frown" , "\\frown"],
    ["wr" , "wr" , "\\wr"],
    ["diamondsuit" , "diamondsuit" , "\\diamondsuit"],
    ["heartsuit" , "heartsuit" , "\\heartsuit"],
    ["clubsuit" , "clubsuit" , "\\clubsuit"],
    ["spadesuit" , "spadesuit" , "\\spadesuit"],
    ["Game" , "Game" , "\\Game"],
    ["flat" , "flat" , "\\flat"],
    ["natural" , "natural" , "\\natural"],
    ["sharp" , "sharp" , "\\sharp"],
    ["diagup" , "diagup" , "\\diagup"],
    ["diagdown" , "diagdown" , "\\diagdown"],
    ["centerdot" , "centerdot" , "\\centerdot"],
    ["ltimes" , "ltimes" , "\\ltimes"],
    ["rtimes" , "rtimes" , "\\rtimes"],
    ["leftthreetimes" , "leftthreetimes" , "\\leftthreetimes"],
    ["rightthreetimes" , "rightthreetimes" , "\\rightthreetimes"],
    ["eqcirc" , "eqcirc" , "\\eqcirc"],
    ["circeq" , "circeq" , "\\circeq"],
    ["triangleq" , "triangleq" , "\\triangleq"],
    ["bumpeq" , "bumpeq" , "\\bumpeq"],
    ["Bumpeq" , "Bumpeq" , "\\Bumpeq"],
    ["risingdotseq" , "risingdotseq" , "\\risingdotseq"],
    ["fallingdotseq" , "fallingdotseq" , "\\fallingdotseq"],
    ["intercal" , "intercal" , "\\intercal"],
    ["barwedge" , "barwedge" , "\\barwedge"],
    ["veebar" , "veebar" , "\\veebar"],
    ["doublebarwedge" , "doublebarwedge" , "\\doublebarwedge"],
    ["between" , "between" , "\\between"],
    ["pitchfork" , "pitchfork" , "\\pitchfork"],
    ["vartriangleleft" , "vartriangleleft" , "\\vartriangleleft"],
    ["ntriangleleft" , "ntriangleleft" , "\\ntriangleleft"],
    ["vartriangleright" , "vartriangleright" , "\\vartriangleright"],
    ["ntriangleright" , "ntriangleright" , "\\ntriangleright"],
    ["trianglelefteq" , "trianglelefteq" , "\\trianglelefteq"],
    ["ntrianglelefteq" , "ntrianglelefteq" , "\\ntrianglelefteq"],
    ["trianglerighteq" , "trianglerighteq" , "\\trianglerighteq"],
    ["ntrianglerighteq" , "ntrianglerighteq" , "\\ntrianglerighteq"],
    

    //分数
    ["frac" , "frac{}{}" , "\\frac{ \\Box }{ \\Box}" , -4 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}],
    ["tfrac" , "tfrac{}{}" , "\\tfrac{ \\Box }{ \\Box}" , -4 , {zoom:'90%',position:'relative',top: '2px',paddingRight:'0px'}],
    ["dfrac" , "dfrac{}{}" , "\\dfrac{ \\Box }{ \\Box}" , -4 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}],
    ["cfrac" , "cfrac{}{}" , "\\cfrac{ \\Box }{ \\Box}" , -4 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}],
    ["over" , "over " , " \\small \\Box \\over \\small \\Box" , -6 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}],
    ["cancel" , "cancel{}" , "\\cancel{x}" , -2 ],

    //标准函数值
    ["exp" , "exp" , "\\exp"],
    ["ln" , "ln" , "\\ln"],
    ["lg" , "lg" , "\\lg"],
    ["log" , "log" , "\\log"],
    ["sin" , "sin" , "\\sin"],
    ["cos" , "cos" , "\\cos"],
    ["tan" , "tan" , "\\tan"],
    ["cot" , "cot" , "\\cot"],
    ["sec" , "sec" , "\\sec"],
    ["csc" , "csc" , "\\csc"],
    ["arcsin" , "arcsin" , "\\arcsin"],
    ["arccos" , "arccos" , "\\arccos"],
    ["arctan" , "arctan" , "\\arctan"],
    ["operatorname" , "operatorname{}" , ""],
    ["sinh" , "sinh" , "\\sinh"],
    ["cosh" , "cosh" , "\\cosh"],
    ["tanh" , "tanh" , "\\tanh"],
    ["coth" , "coth" , "\\coth"],
    ["min" , "min" , "\\min"],
    ["max" , "max" , "\\max"],

    //根式
    ["surd" , "surd" , "\\surd"],
    ["sqrt" , "sqrt{}" , "\\sqrt{\\Box}" , -2],
    ["sqrt" , "sqrt[]{}" , "\\sqrt[n]{\\Box}" , -4],

    //微分与导数
    ["mathrm" , "mathrm{}" , "\\mathrm{A}",-2],

    ["lim" , "lim_{ \\to }" , "\\lim_{\\Box \\to \\Box}" , -7],
    ["lim" , "lim\\nolimits_{ \\to }" , "\\lim\\nolimits_{\\Box \\to \\Box}" , -7],

    
    ["sup" , "sup" , "\\sup"],
    ["inf" , "inf" , "\\inf"],
    ["dim" , "dim" , "\\dim"],
    ["deg" , "deg" , "\\deg"],
    ["det" , "det" , "\\det"],
    ["ker" , "ker" , "\\ker"],
    ["Pr" , "Pr" , "\\Pr"],
    ["hom" , "hom" , "\\hom"],
    ["lVert " , "\lVert  \\lVert " , "\\lVert \\Box \\lVert" , -8],
    
    //积分
    ["int" , "int\\limits_{  }^{  }" , "\\int\\limits_{\\Box}^{\\Box}" , -8 , {zoom:'46%',position:'relative',top: '19px',paddingRight:'16px'}],
    ["int" , "int_{  }^{  }" , "\\int_{\\Box}^{\\Box}" , -8 , {zoom:'62%',position:'relative',top: '11px',paddingRight:'0px'} ],

    ["iint" , "iint\\limits_{  }" , "\\iint\\limits_{D}" , -3 , {zoom:'57%',position:'relative',top: '12px',paddingRight:'6px'}],
    ["iiint" , "iiint\\limits_{  }" , "\\iiint\\limits_{E}" , -3 , {zoom:'58%',position:'relative',top: '12px',paddingRight:'-2px'}],
    ["iiiint" , "iiiint\\limits_{  }" , "\\iiiint\\limits_{E}" , -3 , {zoom:'58%',position:'relative',top: '12px',paddingRight:'-2px'}],

    ["oint" , "oint_{  }" , "\\oint_{\\Box}" , -3 , {zoom:'70%',position:'relative',top: '7px',paddingRight:'4px'}],
    ["oint" , "oint\\limits_{  }" , "\\oint\\limits_{\\Box}" , -3 , {zoom:'56%',position:'relative',top: '13px',paddingRight:'14px'}],
    ["oiint" , "unicode{x222F}" , "\\unicode{x222F}" ],
    ["oiiint" , "unicode{x2230}" , "\\unicode{x2230}" ],
    
    //大型运算
    ["sum" , "sum_{}^{}" , "\\sum_{\\Box}^{\\Box}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'} ],
    ["sum" , "textstyle \\sum_{}^{}" , "\\textstyle \\sum_{\\Box}^{\\Box}" , -5 , {zoom:'85%',position:'relative',top: '3px',}  ],
    ["prod" , "prod_{}^{}" , "\\prod_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["prod" , "textstyle \\prod_{}^{}" , "\\textstyle \\prod_{a}^{b}" , -5   ],

    ["coprod" , "coprod_{}^{}" , "\\coprod_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["coprod" , "textstyle \\coprod_{}^{}" , "\\textstyle \\coprod_{a}^{b}" , -5   ],

    ["bigcap" , "bigcap_{}^{}" , "\\bigcap_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["bigcap" , "textstyle \\bigcap_{}^{}" , "\\textstyle \\bigcap_{a}^{b}" , -5   ],

    ["bigcup" , "bigcup_{}^{}" , "\\bigcup_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["bigcup" , "textstyle \\bigcup_{}^{}" , "\\textstyle \\bigcup_{a}^{b}" , -5   ],

    ["bigvee" , "bigvee_{}^{}" , "\\bigvee_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["bigvee" , "textstyle \\bigvee_{}^{}" , "\\textstyle \\bigvee_{a}^{b}" , -5   ],

    ["bigwedge" , "bigwedge_{}^{}" , "\\bigwedge_{a}^{b}" , -5 , {zoom:'60%',position:'relative',top: '11px',paddingRight:'10px'}  ],
    ["bigwedge" , "textstyle \\bigwedge_{}^{}" , "\\textstyle \\bigwedge_{a}^{b}" , -5   ],

    //上下标
    ["sideset" , "sideset{_1^2}{_3^4}X" , "\\sideset{_1^2}{_3^4}X" , -9   ],
    ["stackrel" , "stackrel{}{}" , "\\stackrel{u}{\\Box}" , -4],
    ["prime" , "prime" , "\\prime"],
    ["dot" , "dot{}" , "\\dot{x}" , -2],
    ["ddot" , "ddot{}" , "\\ddot{x}" , -2],
    
    ["hat" , "hat{}" , "\\hat x" ,-2],
    ["bar" , "bar{}" , "\\bar x" ,-2],
    ["vec" , "vec{}" , "\\vec x" ,-2],

    ["overrightarrow" , "overrightarrow{}" , "\\overrightarrow{abc}" , -2 ,  {zoom:'90%'}],
    ["overleftarrow" , "overleftarrow{}" , "\\overleftarrow{abc}" , -2 ,  {zoom:'90%'}],
    ["widehat" , "widehat{}" , "\\widehat{abc}" , -2 ,  {zoom:'90%'}],
    ["underline" , "underline{}" , "\\underline{abc}" , -2 ,  {zoom:'90%'}],

    ["overset" , "overset{\\frown} {}" , "\\overset{\\frown} {AB}" , -2 ,  {zoom:'90%'}],
    
    ["xleftarrow" , "xleftarrow{}" , "\\xleftarrow{abcd}" , -2 ,  {zoom:'90%'}],
    ["xrightarrow" , "xrightarrow{}" , "\\xrightarrow{abcd}" , -2 ,  {zoom:'90%'}],

    ["overbrace" , "overbrace{}^{}" , "\\overbrace{\\Box \\Box \\Box}^{n}" , -2 ,  {zoom:'70%',position:'relative',top: '7px'}],
    ["underbrace" , "underbrace{}^{}" , "\\underbrace{\\Box \\Box \\Box}^{n}" , -2 ,  {zoom:'70%',position:'relative',top: '7px'}],

    //矩阵
    ["binom" , "binom{}{}" , "\\binom{n}{k}" , -4 ,  {zoom:'60%',position:'relative',top: '10px'}],
    ["tbinom" , "tbinom{}{}" , "\\tbinom{n}{k}" , -4 ,  {zoom:'85%',position:'relative',top: '4px', right:"-4px"}],
    ["dbinom" , "dbinom{}{}" , "\\dbinom{n}{k}" , -4 ,  {zoom:'60%',position:'relative',top: '10px'}],

    //矩阵
    ["matrix" , "begin{matrix}\n   &  \\\\ \n   & \n\\end{matrix}" , "\\begin{matrix}\nx & y \\\\ \nz & v\n\\end{matrix}" , -27 ,  {zoom:'65%',position:'relative',top: '9px'}],
    ["vmatrix" , "begin{vmatrix}\n   &  \\\\ \n   & \n\\end{vmatrix}" , "\\begin{vmatrix}\nx & y \\\\ \nz & v\n\\end{vmatrix}" , -28 ,  {zoom:'60%',position:'relative',top: '10px' , right:"-5px"}],
    ["Vmatrix" , "begin{Vmatrix}\n   &  \\\\ \n   & \n\\end{Vmatrix}" , "\\begin{Vmatrix}\nx & y \\\\ \nz & v\n\\end{Vmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["bmatrix" , "begin{bmatrix}\n   &  \\\\ \n   & \n\\end{bmatrix}" , "\\begin{bmatrix}\nx & y \\\\ \nz & v\n\\end{bmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["Bmatrix" , "begin{Bmatrix}\n   &  \\\\ \n   & \n\\end{Bmatrix}" , "\\begin{Bmatrix}\nx & y \\\\ \nz & v\n\\end{Bmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["pmatrix" , "begin{pmatrix}\n   &  \\\\ \n   & \n\\end{pmatrix}" , "\\begin{pmatrix}\nx & y \\\\ \nz & v\n\\end{pmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],

    //多项式
    ["cases" , "begin{cases}\n  &  \\\\\n & \n\\end{cases}" , "\\begin{cases}\ny=x \\\\\n y=x^2 \n\\end{cases}" , -20 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],

    ["cases" , "begin{cases}\n    &  \\\\\n    & \n\\end{cases}" , "\\begin{cases}\nf(x)=x, & x<0 \\\\\n f(x)=x^2+1, & x\\ge 0 \n\\end{cases}" , -27 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["align" , "begin{align}\n    &  \\\\\n    & \n\\end{align}" , "\\begin{align}\nf(x)= & (a+b)^2 \\\\\n = & a^2+2ab+b^2  \n\\end{align}" , -27 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["alignat" , "begin{alignat}{}\n    &  \\\\\n    & \n\\end{alignat}" , "\\begin{alignat}{2}\nf(x)= & (a+b)^2 \\\\\n = & a^2+2ab+b^2  \n\\end{alignat}" , -27 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["array" , "begin{array}{|c|c|c|}\n  & & \\\\\n \\hline \n  & &  \\\\\n  & & \n\\end{array}" , "\\begin{array}{|c|c|c|}\n a & b & c \\\\\n \\hline \n 0 & 0 & 0 \\\\\n  0 & 0 & 0  \n\\end{array}" , -45 ,  {zoom:'39%',position:'relative',top: '27px' , right:"-5px"}],
    ["array" , "begin{array}{ccc}\n  & & \\\\\n\\end{array}" , "\\begin{array}{ccc}\n f(x) & = & (a+b)^2 \\\\\n f(x) & = & a^2+2ab+b^2  \n\\end{array}" , -20 ,  {zoom:'39%',position:'relative',top: '27px' , right:"-5px"}],


    //矩阵
    ["beginmatrix" , "begin{matrix}\n   &  \\\\ \n   & \n\\end{matrix}" , "\\begin{matrix}\nx & y \\\\ \nz & v\n\\end{matrix}" , -27 ,  {zoom:'65%',position:'relative',top: '9px'}],
    ["beginvmatrix" , "begin{vmatrix}\n   &  \\\\ \n   & \n\\end{vmatrix}" , "\\begin{vmatrix}\nx & y \\\\ \nz & v\n\\end{vmatrix}" , -28 ,  {zoom:'60%',position:'relative',top: '10px' , right:"-5px"}],
    ["beginVmatrix" , "begin{Vmatrix}\n   &  \\\\ \n   & \n\\end{Vmatrix}" , "\\begin{Vmatrix}\nx & y \\\\ \nz & v\n\\end{Vmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginbmatrix" , "begin{bmatrix}\n   &  \\\\ \n   & \n\\end{bmatrix}" , "\\begin{bmatrix}\nx & y \\\\ \nz & v\n\\end{bmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginBmatrix" , "begin{Bmatrix}\n   &  \\\\ \n   & \n\\end{Bmatrix}" , "\\begin{Bmatrix}\nx & y \\\\ \nz & v\n\\end{Bmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginpmatrix" , "begin{pmatrix}\n   &  \\\\ \n   & \n\\end{pmatrix}" , "\\begin{pmatrix}\nx & y \\\\ \nz & v\n\\end{pmatrix}" , -28 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],

    //多项式
    ["begincases" , "begin{cases}\n  &  \\\\\n  & \n\\end{cases}" , "\\begin{cases}\ny=x \\\\\n y=x^2 \n\\end{cases}" , -24 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],

    ["begincases" , "begin{cases}\n    &  \\\\\n    & \n\\end{cases}" , "\\begin{cases}\nf(x)=x, & x<0 \\\\\n f(x)=x^2+1, & x\\ge 0 \n\\end{cases}" , -27 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginalign" , "begin{align}\n    &  \\\\\n    & \n\\end{align}" , "\\begin{align}\nf(x)= & (a+b)^2 \\\\\n = & a^2+2ab+b^2  \n\\end{align}" , -27 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginalignat" , "begin{alignat}{}\n    &  \\\\\n    & \n\\end{alignat}" , "\\begin{alignat}{2}\nf(x)= & (a+b)^2 \\\\\n = & a^2+2ab+b^2  \n\\end{alignat}" , -29 ,  {zoom:'55%',position:'relative',top: '14px' , right:"-5px"}],
    ["beginarray" , "begin{array}{|c|c|c|}\n  & & \\\\\n \\hline \n  & &  \\\\\n  & & \n\\end{array}" , "\\begin{array}{|c|c|c|}\n a & b & c \\\\\n \\hline \n 0 & 0 & 0 \\\\\n  0 & 0 & 0  \n\\end{array}" , -46 ,  {zoom:'39%',position:'relative',top: '27px' , right:"-5px"}],
    ["beginarray" , "begin{array}{ccc}\n  & & \\\\\n\\end{array}" , "\\begin{array}{ccc}\n f(x) & = & (a+b)^2 \\\\\n f(x) & = & a^2+2ab+b^2  \n\\end{array}" , -20 ,  {zoom:'39%',position:'relative',top: '27px' , right:"-5px"}],

    
    //括号
    ["lbrack " , "lbrack" , "\\lbrack"],
    ["rbrack " , "rbrack" , "\\rbrack"],
    ["lbrace  " , "lbrace" , "\\lbrace"],
    ["rbrace  " , "rbrace" , "\\rbrace"],
    ["langle   " , "langle" , "\\langle"],
    ["rangle   " , "rangle" , "\\rangle"],
    ["vert" , "vert" , "\\vert"],
    ["Vert" , "Vert" , "\\Vert"],
    ["lfloor" , "lfloor" , "\\lfloor"],
    ["rfloor" , "rfloor" , "\\rfloor"],
    ["lceil" , "lceil" , "\\lceil"],
    ["rceil" , "rceil" , "\\rceil"],

    //换行
    ["displaylines" , "displaylines{}" , "\\displaylines{}" , -2],

    //颜色
    ["color" , "color{}" , "{\\color{Green}color}" , -2],
    ["colorbox" , "colorbox{}{}" , "{\\colorbox{Green}{colorbox}}" , -4],
    ["bbox" , "bbox[]{}" , "{\\bbox[green,2pt]{bbox}}" , -4],
    ["definecolor" , "definecolor{}{RGB}{}" , "" , -9],
    
]   